const $=s=>document.querySelector(s),c=$('#ritualCanvas'),x=c.getContext('2d'),p=$('#previewCanvas'),z=p.getContext('2d');
let ps=[],trail=[],mode='collect',pt,core,amount=0,choice='open',dragStart,dragStartedAt;const escapeRadius=90,grabRadius=160;const pages=['intro','ritual','result'].map(id=>$('#'+id));
const wallpaperSources={open:['images/randam/hiraku-celestite.png','images/randam/hiraku-chrysoprase.png','images/randam/hiraku-green-apophyllit.png','images/randam/hiraku-kunzite.png','images/randam/hiraku-kyanite.png','images/randam/hiraku-lapis-lazul.png','images/randam/hiraku-sapphire.png','images/randam/hiraku-smoky-quartz.png','images/randam/hiraku-sodalite.png','images/randam/hiraku-turquoise-2.png','images/randam/hiraku-turquoise.png'],rest:['images/randam/yasumu-amazonite.png','images/randam/yasumu-amethyst-yasumu-macro-1.png','images/randam/yasumu-blue-topaz-macro-1.png','images/randam/yasumu-charoite-macro-1.png','images/randam/yasumu-fire-agate.png','images/randam/yasumu-howlite-macro-1.png','images/randam/yasumu-lapis-lazuli-macro-1.png','images/randam/yasumu-lepidolite-macro-1.png','images/randam/yasumu-rhodochrosite-macro-1.png','images/randam/yasumu-rose-quartz-macro-1.png','images/randam/yasumu-sunstone-macro-1.png'],grow:['images/randam/sodateru-black-tourmaline.png','images/randam/sodateru-carnelian.png','images/randam/sodateru-hematite.png','images/randam/sodateru-labradorite.png','images/randam/sodateru-meteorite.png','images/randam/sodateru-onyx.png','images/randam/sodateru-rainbow-obsidian.png','images/randam/sodateru-red-topa.png','images/randam/sodateru-ruby.png','images/randam/sodateru-tiger-eye-hiraku.png','images/randam/sodateru-vanadinite.png'],flow:['images/randam/nagasu-aquamarine.png','images/randam/nagasu-citrine.png','images/randam/nagasu-clear-quartz.png','images/randam/nagasu-fluorite.png','images/randam/nagasu-green-aventurine.png','images/randam/nagasu-larimar-white-matrix.png','images/randam/nagasu-malachite.png','images/randam/nagasu-moldavite.png','images/randam/nagasu-moonstone.png','images/randam/nagasu-opal.png','images/randam/nagasu-peridot.png']};
const msg=['余白が戻ってきました','少し風通しがよくなりました','今日はここまでで十分です','ひと息つけそうです','重たさが、ひとつ流れました','今日はこれで、だいじょうぶ','なんか、少し軽い','いい風、通ってます','ここからまた、ゆっくり','きれいに流れていきました','ひと息ぶん、軽くなりました','急がなくていい日','気持ちの置き場、できました'];
function size(){let d=Math.min(devicePixelRatio,2);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0)}
function start(){size();ps=Array.from({length:85},()=>({X:Math.random()*innerWidth,Y:Math.random()*innerHeight,r:8+Math.random()*18,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3,a:.22,on:false}));mode='collect';amount=0;trail=[];$('#progressBar').style.width=0;$('#statusLabel').textContent='モヤモヤを手放す準備中';$('#guideLabel').textContent='モヤをぐるぐる集めてね';$('#stepLabel').textContent='STEP 01';$('#nextButton').disabled=true}
function frame(){if(!$('#ritual').classList.contains('active'))return;let g=x.createRadialGradient(innerWidth/2,innerHeight*.45,0,innerWidth/2,innerHeight/2,innerWidth*.8);g.addColorStop(0,'#312a4a');g.addColorStop(1,'#0e0e1d');x.fillStyle=g;x.fillRect(0,0,innerWidth,innerHeight);ps.forEach(q=>{if(pt&&mode==='collect'){let dx=pt.X-q.X,dy=pt.Y-q.Y,d=Math.hypot(dx,dy);if(d<155){q.vx+=dx/d*.06;q.vy+=dy/d*.06;q.on=true}}if(core&&q.on){q.X+=(core.X-q.X)*.05;q.Y+=(core.Y-q.Y)*.05;q.a*=.96}else{q.X+=q.vx;q.Y+=q.vy}let h=x.createRadialGradient(q.X,q.Y,0,q.X,q.Y,q.r);h.addColorStop(0,`rgba(25,20,35,${q.a*2})`);h.addColorStop(1,'transparent');x.fillStyle=h;x.beginPath();x.arc(q.X,q.Y,q.r,0,7);x.fill()});trail.forEach(t=>{t.a-=.025;x.strokeStyle=`rgba(235,210,255,${t.a*.35})`;x.beginPath();x.arc(t.X,t.Y,t.r,0,7);x.stroke()});trail=trail.filter(t=>t.a>0);if(core){x.fillStyle='#211b2cee';x.beginPath();x.arc(core.X,core.Y,48,0,7);x.fill()}requestAnimationFrame(frame)}
function point(e){let r=c.getBoundingClientRect();return{X:e.clientX-r.left,Y:e.clientY-r.top}}
function hasEscaped(n){return n.X<=escapeRadius||n.X>=c.clientWidth-escapeRadius||n.Y<=escapeRadius||n.Y>=c.clientHeight-escapeRadius}
c.onpointerdown=e=>{pt=point(e);if(mode==='throw'&&Math.hypot(pt.X-core.X,pt.Y-core.Y)<grabRadius){mode='drag';dragStart=pt;dragStartedAt=performance.now();c.setPointerCapture(e.pointerId)}};
c.onpointermove=e=>{let n=point(e);if(mode==='drag'){core=n;if(hasEscaped(n))clear();return}if(mode==='collect'&&pt){let d=Math.hypot(n.X-pt.X,n.Y-pt.Y);if(d>6){amount=Math.min(100,amount+d*.045);trail.push({X:n.X,Y:n.Y,r:20,a:1});progress()}pt=n}};c.onpointerup=e=>{if(mode==='collect')pt=null;if(mode==='drag'){let n=point(e),flung=dragStart&&Math.hypot(n.X-dragStart.X,n.Y-dragStart.Y)>110&&performance.now()-dragStartedAt<900;if(hasEscaped(n)||flung)clear();else mode='throw'}if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId)};c.onpointercancel=e=>{if(mode==='drag')mode='throw';if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId)};
function progress(){$('#progressBar').style.width=amount+'%';if(amount>28)$('#statusLabel').textContent='ゆっくり、ぐるぐる…';if(amount>65)$('#statusLabel').textContent='モヤがほどけてきた';if(amount>=100){$('#statusLabel').textContent='モヤが集まりました';$('#guideLabel').textContent='払い落とせそう！';$('#nextButton').disabled=false}}
$('#nextButton').onclick=()=>{mode='throw';core={X:innerWidth/2,Y:innerHeight/2};$('#stepLabel').textContent='STEP 02';$('#guideLabel').textContent='画面の外へ、えいっ！';$('#guideLabel').classList.add('throw-guide');$('#ritual').classList.add('is-throwing');$('#nextButton').style.display='none'};
function clear(){mode='done';ps.forEach(q=>q.a=0);$('#success').classList.add('show');setTimeout(()=>$('#afterglowChoice').classList.add('show'),1000)}
function renderWallpaper(image){let w=1440,h=3200;p.width=w;p.height=h;let scale=Math.max(w/image.naturalWidth,h/image.naturalHeight),drawW=image.naturalWidth*scale,drawH=image.naturalHeight*scale;z.drawImage(image,(w-drawW)/2,(h-drawH)/2,drawW,drawH)}
function result(){$('#resultMessage').textContent=msg[Math.floor(Math.random()*msg.length)];let sources=wallpaperSources[choice]||wallpaperSources.open,source=sources[Math.floor(Math.random()*sources.length)],image=new Image();image.onload=()=>renderWallpaper(image);image.onerror=()=>{z.fillStyle='#171526';z.fillRect(0,0,p.width||1440,p.height||3200)};image.src=source;$('#ritual').classList.remove('active');$('#result').classList.add('active')}
$('#startButton').onclick=()=>{$('#intro').classList.remove('active');$('#ritual').classList.add('active');$('#ritual').classList.remove('is-throwing');$('#guideLabel').classList.remove('throw-guide');start();frame()};document.querySelectorAll('[data-afterglow]').forEach(b=>b.onclick=()=>{choice=b.dataset.afterglow;document.body.dataset.afterglow=choice;result()});$('#saveButton').onclick=()=>{let a=document.createElement('a');a.download='yakuyoke-wallpaper.png';a.href=p.toDataURL();a.click()};$('#shareButton').onclick=()=>open('https://x.com/intent/post?text='+encodeURIComponent('厄をひとつ払ってみた #厄落としメーカー #オカルトかーちゃん'),'_blank');$('#replayButton').onclick=()=>{$('#result').classList.remove('active');$('#intro').classList.add('active');$('#ritual').classList.remove('is-throwing');$('#guideLabel').classList.remove('throw-guide');$('#success').classList.remove('show');$('#afterglowChoice').classList.remove('show');$('#nextButton').style.display='block'};onresize=size;
