const $=s=>document.querySelector(s),c=$('#ritualCanvas'),x=c.getContext('2d'),p=$('#previewCanvas'),z=p.getContext('2d');
let ps=[],trail=[],mode='collect',pt,core,amount=0,choice='open';const escapeRadius=48;const pages=['intro','ritual','result'].map(id=>$('#'+id));
const msg=['余白が戻ってきました','少し風通しがよくなりました','今日はここまでで十分です','ひと息つけそうです','重たさが、ひとつ流れました','今日はこれで、だいじょうぶ','なんか、少し軽い','いい風、通ってます','ここからまた、ゆっくり','きれいに流れていきました','ひと息ぶん、軽くなりました','急がなくていい日','気持ちの置き場、できました'];
function size(){let d=Math.min(devicePixelRatio,2);c.width=innerWidth*d;c.height=innerHeight*d;x.setTransform(d,0,0,d,0,0)}
function start(){size();ps=Array.from({length:85},()=>({X:Math.random()*innerWidth,Y:Math.random()*innerHeight,r:8+Math.random()*18,vx:(Math.random()-.5)*.3,vy:(Math.random()-.5)*.3,a:.22,on:false}));mode='collect';amount=0;trail=[];$('#progressBar').style.width=0;$('#statusLabel').textContent='モヤモヤを手放す準備中';$('#guideLabel').textContent='モヤをぐるぐる集めてね';$('#stepLabel').textContent='STEP 01';$('#nextButton').disabled=true}
function frame(){if(!$('#ritual').classList.contains('active'))return;let g=x.createRadialGradient(innerWidth/2,innerHeight*.45,0,innerWidth/2,innerHeight/2,innerWidth*.8);g.addColorStop(0,'#312a4a');g.addColorStop(1,'#0e0e1d');x.fillStyle=g;x.fillRect(0,0,innerWidth,innerHeight);ps.forEach(q=>{if(pt&&mode==='collect'){let dx=pt.X-q.X,dy=pt.Y-q.Y,d=Math.hypot(dx,dy);if(d<155){q.vx+=dx/d*.06;q.vy+=dy/d*.06;q.on=true}}if(core&&q.on){q.X+=(core.X-q.X)*.05;q.Y+=(core.Y-q.Y)*.05;q.a*=.96}else{q.X+=q.vx;q.Y+=q.vy}let h=x.createRadialGradient(q.X,q.Y,0,q.X,q.Y,q.r);h.addColorStop(0,`rgba(25,20,35,${q.a*2})`);h.addColorStop(1,'transparent');x.fillStyle=h;x.beginPath();x.arc(q.X,q.Y,q.r,0,7);x.fill()});trail.forEach(t=>{t.a-=.025;x.strokeStyle=`rgba(235,210,255,${t.a*.35})`;x.beginPath();x.arc(t.X,t.Y,t.r,0,7);x.stroke()});trail=trail.filter(t=>t.a>0);if(core){x.fillStyle='#211b2cee';x.beginPath();x.arc(core.X,core.Y,48,0,7);x.fill()}requestAnimationFrame(frame)}
function point(e){let r=c.getBoundingClientRect();return{X:e.clientX-r.left,Y:e.clientY-r.top}}
function hasEscaped(n){return n.X<=escapeRadius||n.X>=c.clientWidth-escapeRadius||n.Y<=escapeRadius||n.Y>=c.clientHeight-escapeRadius}
c.onpointerdown=e=>{pt=point(e);if(mode==='throw'&&Math.hypot(pt.X-core.X,pt.Y-core.Y)<90){mode='drag';c.setPointerCapture(e.pointerId)}};
c.onpointermove=e=>{let n=point(e);if(mode==='drag'){core=n;if(hasEscaped(n))clear();return}if(mode==='collect'&&pt){let d=Math.hypot(n.X-pt.X,n.Y-pt.Y);if(d>6){amount=Math.min(100,amount+d*.045);trail.push({X:n.X,Y:n.Y,r:20,a:1});progress()}pt=n}};c.onpointerup=e=>{if(mode==='collect')pt=null;if(mode==='drag'){if(hasEscaped(point(e)))clear();else mode='throw'}if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId)};c.onpointercancel=e=>{if(mode==='drag')mode='throw';if(c.hasPointerCapture(e.pointerId))c.releasePointerCapture(e.pointerId)};
function progress(){$('#progressBar').style.width=amount+'%';if(amount>28)$('#statusLabel').textContent='ゆっくり、ぐるぐる…';if(amount>65)$('#statusLabel').textContent='モヤがほどけてきた';if(amount>=100){$('#statusLabel').textContent='モヤが集まりました';$('#guideLabel').textContent='払い落とせそう！';$('#nextButton').disabled=false}}
$('#nextButton').onclick=()=>{mode='throw';core={X:innerWidth/2,Y:innerHeight/2};$('#stepLabel').textContent='STEP 02';$('#guideLabel').textContent='そのまま画面の外へ、えいっ！';$('#nextButton').style.display='none'};
function clear(){mode='done';ps.forEach(q=>q.a=0);$('#success').classList.add('show');setTimeout(()=>$('#afterglowChoice').classList.add('show'),1000)}
function motif(){let X=720,Y=1850;z.save();z.strokeStyle=z.fillStyle='#fff1be';z.globalAlpha=.56;if(choice==='open'){for(let i=0;i<20;i++){let a=i*Math.PI/10;z.beginPath();z.moveTo(X+Math.cos(a)*80,Y+Math.sin(a)*80);z.lineTo(X+Math.cos(a)*520,Y+Math.sin(a)*520);z.stroke()}}else if(choice==='rest'){z.beginPath();z.arc(X,Y,220,0,7);z.fill();z.globalCompositeOperation='destination-out';z.beginPath();z.arc(X+85,Y-65,220,0,7);z.fill()}else if(choice==='grow'){for(let i=0;i<8;i++){let a=i*Math.PI/4;z.beginPath();z.ellipse(X+Math.cos(a)*170,Y+Math.sin(a)*170,45,120,a,0,7);z.fill()}z.beginPath();z.arc(X,Y,65,0,7);z.fill()}else{for(let i=0;i<6;i++){z.globalAlpha=.52-i*.07;z.lineWidth=10;z.beginPath();z.arc(X,Y,110+i*92,.4,5.9);z.stroke()}}z.restore()}
function result(){$('#resultMessage').textContent=msg[Math.floor(Math.random()*msg.length)];let w=1440,h=3200,colors=[['#18233f','#6b5b91','#e7cc92'],['#102a42','#426d92','#b7e3dd'],['#291b42','#76578d','#ddc7ee']][Math.floor(Math.random()*3)],g=z.createLinearGradient(0,0,w,h);p.width=w;p.height=h;g.addColorStop(0,colors[0]);g.addColorStop(.55,colors[1]);g.addColorStop(1,colors[2]);z.fillStyle=g;z.fillRect(0,0,w,h);for(let i=0;i<130;i++){z.fillStyle='rgba(255,255,255,.45)';z.beginPath();z.arc(Math.random()*w,Math.random()*h,2+Math.random()*5,0,7);z.fill()}motif();z.textAlign='center';z.fillStyle='#fff8df';z.font='38px serif';z.fillText('オカルトかーちゃん',720,h-150);z.font='29px serif';z.fillText($('#resultMessage').textContent,720,h-95);$('#ritual').classList.remove('active');$('#result').classList.add('active')}
$('#startButton').onclick=()=>{$('#intro').classList.remove('active');$('#ritual').classList.add('active');start();frame()};document.querySelectorAll('[data-afterglow]').forEach(b=>b.onclick=()=>{choice=b.dataset.afterglow;result()});$('#saveButton').onclick=()=>{let a=document.createElement('a');a.download='yakuyoke-wallpaper.png';a.href=p.toDataURL();a.click()};$('#shareButton').onclick=()=>open('https://x.com/intent/post?text='+encodeURIComponent('厄をひとつ払ってみた #厄落としメーカー #オカルトかーちゃん'),'_blank');$('#replayButton').onclick=()=>{$('#result').classList.remove('active');$('#intro').classList.add('active');$('#success').classList.remove('show');$('#afterglowChoice').classList.remove('show');$('#nextButton').style.display='block'};onresize=size;
